/**
 * ProfileAnnotationPanel.tsx
 * 2D profile viewer with engineering dimension annotations.
 * Uses react-konva for canvas rendering — no SVG, no CDN.
 *
 * Data: pipelineResult.roll_contour_engine.passes[].profile_centerline
 * Each profile_centerline is [{x, y}] in mm, generated by section_centerline()
 * using the REAL forming angle at that station.
 */

import { useState, useMemo, useCallback } from "react";
import { Stage, Layer, Line, Circle, Text, Group, Arrow, Rect } from "react-konva";
import {
  ChevronLeft, ChevronRight, SkipBack, SkipForward,
  Ruler, Download, Eye, EyeOff,
} from "lucide-react";

// ─── Interfaces ───────────────────────────────────────────────────────────────
interface Pt2 { x: number; y: number }

interface ContactStrip {
  strip_type: string;
  x_from: number; x_to: number;
  y_from: number; y_to: number;
  color: string;
  label: string;
}

interface PinchZone {
  zone_type: string;
  x: number; y: number;
  label: string;
  severity?: string;
}

interface RollWidthBreakdown {
  web_contact_mm?:        number;
  flange_support_mm?:     number;
  edge_relief_mm?:        number;
  shoulder_clearance_mm?: number;
  total_face_mm?:         number;
}

interface PassData {
  pass_no:                number;
  station_label:          string;
  target_angle_deg:       number;
  stage_type:             string;
  strip_width_mm?:        number;
  roll_gap_mm?:           number;
  profile_centerline?:    Pt2[];
  contact_points?:        Pt2[];
  upper_roll_profile?:    Pt2[] | null;
  lower_roll_profile?:    Pt2[] | null;
  // Tooling-grade v2.6
  contact_strips?:        ContactStrip[];
  pinch_zones?:           PinchZone[];
  entry_radius_mm?:       number;
  exit_radius_mm?:        number;
  roll_width_mm?:         number;
  groove_depth_mm?:       number;
  shaft_center_distance_mm?: number;
  roll_width_breakdown?:  RollWidthBreakdown;
  flange_support_width_mm?: number;
  edge_relief_width_mm?:  number;
  edge_relief_depth_mm?:  number;
  geometry_source?:       string;
}

interface Props {
  rollContour: {
    passes?:          PassData[];
    forming_summary?: { flat_strip_width_mm?: number; profile_category?: string };
    thickness_mm?:    number;
  } | null;
  webMm?:           number;
  flangeMm?:        number;
  thicknessMm?:     number;
  profileCategory?: string | null;
}

// ─── Konva helpers ────────────────────────────────────────────────────────────
const W = 640;
const H = 320;

const STAGE_COL: Record<string, string> = {
  flat:                "#94a3b8",
  pre_bend:            "#a78bfa",
  initial_bend:        "#818cf8",
  progressive_forming: "#60a5fa",
  lip_forming:         "#f472b6",
  calibration:         "#4ade80",
  forming:             "#60a5fa",
};

/**
 * Map mm → canvas pixels, fitting within a padded area.
 * Returns a function (x_mm, y_mm) → {x_px, y_px}.
 */
function fitToCanvas(
  pts:     Pt2[],
  canvasW: number,
  canvasH: number,
  pad:     number,
): { toCanvas: (x: number, y: number) => { cx: number; cy: number }; scale: number } {
  if (!pts.length) {
    return { toCanvas: (x, y) => ({ cx: x, cy: y }), scale: 1 };
  }
  const xs = pts.map(p => p.x);
  const ys = pts.map(p => p.y);
  const minX = Math.min(...xs), maxX = Math.max(...xs);
  const minY = Math.min(...ys), maxY = Math.max(...ys);
  const dw   = maxX - minX || 1;
  const dh   = maxY - minY || 1;
  const sx   = (canvasW - 2 * pad) / dw;
  const sy   = (canvasH - 2 * pad) / dh;
  const scale = Math.min(sx, sy);
  const cx0  = (canvasW - dw * scale) / 2 - minX * scale;
  const cy0  = canvasH - pad + minY * scale;  // flip Y (Konva Y down, mm Y up)

  return {
    toCanvas: (x: number, y: number) => ({
      cx: cx0 + x * scale,
      cy: cy0 - y * scale,
    }),
    scale,
  };
}

/** Draw a dimension line with arrows and a text label. */
function DimLine({
  x1, y1, x2, y2, label, color = "#94a3b8", offset = 0,
}: {
  x1: number; y1: number; x2: number; y2: number;
  label: string; color?: string; offset?: number;
}) {
  const dx   = x2 - x1, dy = y2 - y1;
  const len  = Math.sqrt(dx * dx + dy * dy) || 1;
  const nx   = -dy / len, ny = dx / len;  // normal
  const ox   = nx * offset, oy = ny * offset;
  const mx   = (x1 + x2) / 2 + ox * 1.5;
  const my   = (y1 + y2) / 2 + oy * 1.5;

  return (
    <Group>
      {/* Witness lines */}
      <Line points={[x1, y1, x1 + ox, y1 + oy]} stroke={color} strokeWidth={0.7} dash={[3, 3]} opacity={0.5} />
      <Line points={[x2, y2, x2 + ox, y2 + oy]} stroke={color} strokeWidth={0.7} dash={[3, 3]} opacity={0.5} />
      {/* Main dim line with arrows */}
      <Arrow
        points={[x1 + ox, y1 + oy, x2 + ox, y2 + oy]}
        pointerLength={6} pointerWidth={4}
        fill={color} stroke={color} strokeWidth={1}
        pointerAtBeginning pointerAtEnding
      />
      {/* Label */}
      <Rect x={mx - 18} y={my - 7} width={36} height={13} fill="#0a0f1a" cornerRadius={3} />
      <Text
        x={mx - 18} y={my - 6.5}
        text={label} fontSize={9.5} fill={color}
        width={36} align="center" fontFamily="monospace"
      />
    </Group>
  );
}

/** Angle arc annotation at a bend vertex. */
function AngleMark({
  cx, cy, angle_deg, radius = 22, color = "#f59e0b",
}: {
  cx: number; cy: number; angle_deg: number; radius?: number; color?: string;
}) {
  // Draw a small arc showing the angle
  const pts: number[] = [];
  const startDeg = -angle_deg / 2;
  const steps = Math.max(6, Math.round(angle_deg));
  for (let i = 0; i <= steps; i++) {
    const a = ((startDeg + (angle_deg * i) / steps) * Math.PI) / 180;
    pts.push(cx + radius * Math.cos(a), cy - radius * Math.sin(a));
  }
  return (
    <Group>
      <Line points={pts} stroke={color} strokeWidth={1.2} opacity={0.7} />
      <Text
        x={cx - 16} y={cy - radius - 14}
        text={`${angle_deg.toFixed(0)}°`}
        fontSize={9} fill={color} fontFamily="monospace" align="center" width={32}
      />
    </Group>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────
export default function ProfileAnnotationPanel({
  rollContour, webMm = 60, flangeMm = 40, thicknessMm = 1.5, profileCategory,
}: Props) {
  const passes = rollContour?.passes ?? [];
  const n      = passes.length;
  // Resolve profile category from prop or forming_summary
  const profCat = profileCategory ?? rollContour?.forming_summary?.profile_category ?? null;

  const [activeIdx,        setActiveIdx]        = useState(0);
  const [showAll,          setShowAll]          = useState(true);
  const [showDims,         setShowDims]         = useState(true);
  const [showContact,      setShowContact]      = useState(true);
  const [showZones,        setShowZones]        = useState(true);
  const [showPinch,        setShowPinch]        = useState(true);
  const [showHighPinch,    setShowHighPinch]    = useState(true);
  const [showCritPinch,    setShowCritPinch]    = useState(true);

  const go = useCallback((i: number) => setActiveIdx(Math.max(0, Math.min(n - 1, i))), [n]);

  const cur = passes[activeIdx];
  const stageCol = cur ? (STAGE_COL[cur.stage_type] ?? "#60a5fa") : "#60a5fa";

  // Collect all profile points across all passes for consistent scaling
  const allPts = useMemo(() => {
    return passes.flatMap(p => p.profile_centerline ?? []);
  }, [passes]);

  const { toCanvas, scale } = useMemo(() => fitToCanvas(allPts, W, H, 45), [allPts]);

  // Active profile points
  const activePts = useMemo(() => {
    const cl = cur?.profile_centerline;
    if (cl && cl.length >= 2) return cl;
    // Fallback: generate approximate points from angle
    if (!cur) return [];
    const th = (cur.target_angle_deg * Math.PI) / 180;
    const hw = webMm / 2;
    const lx = -Math.cos(th), ly = Math.sin(th);
    const rx =  Math.cos(th), ry = Math.sin(th);
    return [
      { x: -hw + lx * flangeMm, y: ly * flangeMm },
      { x: -hw, y: 0 },
      { x:  hw, y: 0 },
      { x:  hw + rx * flangeMm, y: ry * flangeMm },
    ];
  }, [cur, webMm, flangeMm]);

  const hasReal = (cur?.profile_centerline?.length ?? 0) >= 2;
  const contactPts = cur?.contact_points ?? [];

  if (!n) {
    return (
      <div className="rounded-xl border border-gray-700/40 bg-[#0d1117] p-6">
        <div className="flex items-center gap-2 mb-2">
          <Ruler className="w-4 h-4 text-violet-400" />
          <span className="text-xs font-bold text-violet-300 uppercase tracking-wider">2D Profile Annotations</span>
        </div>
        <div className="h-24 flex items-center justify-center text-gray-600 text-xs">
          Run the pipeline to view annotated cross-sections.
        </div>
      </div>
    );
  }

  // Flatten points for Konva Line
  const toFlat = (pts: Pt2[]) =>
    pts.flatMap(p => { const { cx, cy } = toCanvas(p.x, p.y); return [cx, cy]; });

  // Grid lines in canvas space
  const gridLines = (() => {
    const lines: { x1: number; y1: number; x2: number; y2: number }[] = [];
    const step = 20 * scale;
    if (step < 5) return [];
    for (let g = -200; g <= 200; g++) {
      const { cx } = toCanvas(g * 20, 0);
      if (cx < 0 || cx > W) continue;
      lines.push({ x1: cx, y1: 0, x2: cx, y2: H });
    }
    const { cy } = toCanvas(0, 0);
    lines.push({ x1: 0, y1: cy, x2: W, y2: cy });
    return lines;
  })();

  // Dimension annotations
  const dims = (() => {
    if (!showDims || activePts.length < 4) return null;
    const first = activePts[0];
    const webL  = activePts[1];
    const webR  = activePts[activePts.length - 2];
    const last  = activePts[activePts.length - 1];
    const p1 = toCanvas(webL.x, webL.y);
    const p2 = toCanvas(webR.x, webR.y);
    const p3 = toCanvas(first.x, first.y);
    const p4 = toCanvas(last.x, last.y);
    const webPx = Math.abs(p2.cx - p1.cx);

    return (
      <>
        {/* Web width */}
        <DimLine
          x1={p1.cx} y1={p1.cy} x2={p2.cx} y2={p2.cy}
          label={`${webMm}mm`} color="#60a5fa" offset={-28}
        />
        {/* Left flange */}
        <DimLine
          x1={p1.cx} y1={p1.cy} x2={p3.cx} y2={p3.cy}
          label={`${flangeMm}mm`} color="#4ade80" offset={-18}
        />
        {/* Right flange */}
        <DimLine
          x1={p2.cx} y1={p2.cy} x2={p4.cx} y2={p4.cy}
          label={`${flangeMm}mm`} color="#4ade80" offset={18}
        />
        {/* Angle marks at each bend vertex */}
        {activePts.slice(1, -1).map((pt, i) => {
          const { cx, cy } = toCanvas(pt.x, pt.y);
          return (
            <AngleMark
              key={i} cx={cx} cy={cy}
              angle_deg={cur?.target_angle_deg ?? 0}
              radius={Math.min(22, webPx * 0.22)}
              color="#f59e0b"
            />
          );
        })}
      </>
    );
  })();

  return (
    <div className="rounded-xl border border-gray-700/40 bg-[#0d1117] overflow-hidden">
      {/* Header */}
      <div className="px-4 py-2.5 border-b border-gray-700/50 flex items-center gap-2 flex-wrap">
        <Ruler className="w-4 h-4 text-violet-400 shrink-0" />
        <div>
          <div className="text-xs font-bold text-violet-300 uppercase tracking-wider">2D Profile Annotations</div>
          <div className="text-[10px] text-gray-500 font-mono">
            Konva.js · {hasReal ? "✓ real centerline geometry" : "~ fallback geometry"}
          </div>
        </div>
        <div className="ml-auto flex items-center gap-1.5">
          <button onClick={() => setShowAll(s => !s)}
            className={`p-1.5 rounded border text-[10px] flex items-center gap-1 transition-colors ${
              showAll ? "border-violet-500/30 bg-violet-500/10 text-violet-300" : "border-gray-700 text-gray-600"
            }`}>
            {showAll ? <Eye className="w-3 h-3" /> : <EyeOff className="w-3 h-3" />} All
          </button>
          <button onClick={() => setShowDims(s => !s)}
            className={`p-1.5 rounded border text-[10px] flex items-center gap-1 transition-colors ${
              showDims ? "border-blue-500/30 bg-blue-500/10 text-blue-300" : "border-gray-700 text-gray-600"
            }`}>
            <Ruler className="w-3 h-3" /> Dims
          </button>
          <button onClick={() => setShowZones(s => !s)}
            className={`p-1.5 rounded border text-[10px] flex items-center gap-1 transition-colors ${
              showZones ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-300" : "border-gray-700 text-gray-600"
            }`}>
            <Eye className="w-3 h-3" /> Zones
          </button>
          <button onClick={() => setShowPinch(s => !s)}
            className={`p-1.5 rounded border text-[10px] flex items-center gap-1 transition-colors ${
              showPinch ? "border-amber-500/30 bg-amber-500/10 text-amber-300" : "border-gray-700 text-gray-600"
            }`}>
            <Eye className="w-3 h-3" /> Pinch
          </button>
          <button onClick={() => setShowHighPinch(s => !s)}
            title="Toggle high-severity pinch zones"
            className={`p-1.5 rounded border text-[10px] flex items-center gap-1 transition-colors ${
              showHighPinch ? "border-orange-500/30 bg-orange-500/10 text-orange-300" : "border-gray-700 text-gray-600"
            }`}>
            <Eye className="w-3 h-3" /> High
          </button>
          <button onClick={() => setShowCritPinch(s => !s)}
            title="Toggle critical-severity pinch zones"
            className={`p-1.5 rounded border text-[10px] flex items-center gap-1 transition-colors ${
              showCritPinch ? "border-red-500/30 bg-red-500/10 text-red-300" : "border-gray-700 text-gray-600"
            }`}>
            <Eye className="w-3 h-3" /> Crit
          </button>
          <button onClick={() => setShowContact(s => !s)}
            className={`p-1.5 rounded border text-[10px] flex items-center gap-1 transition-colors ${
              showContact ? "border-red-500/30 bg-red-500/10 text-red-300" : "border-gray-700 text-gray-600"
            }`}>
            <Eye className="w-3 h-3" /> Contact
          </button>
        </div>
      </div>

      {/* Konva canvas */}
      <div className="bg-[#070b12]">
        <Stage width={W} height={H}>
          <Layer>
            {/* Background */}
            <Rect x={0} y={0} width={W} height={H} fill="#070b12" />

            {/* Grid */}
            {gridLines.map((g, i) => (
              <Line key={i} points={[g.x1, g.y1, g.x2, g.y2]}
                stroke="#0f1a2e" strokeWidth={0.7} />
            ))}

            {/* All-pass flower traces (faded) */}
            {showAll && passes.map((p, i) => {
              if (i === activeIdx) return null;
              const cl = p.profile_centerline;
              if (!cl || cl.length < 2) return null;
              const flat = toFlat(cl);
              const opacity = 0.06 + (i / n) * 0.12;
              const col    = STAGE_COL[p.stage_type] ?? "#60a5fa";
              return <Line key={i} points={flat} stroke={col} strokeWidth={1}
                           opacity={opacity} lineCap="round" lineJoin="round" />;
            })}

            {/* Final profile target (red dashed) */}
            {passes.length > 1 && (() => {
              const last = passes[passes.length - 1];
              const cl   = last.profile_centerline;
              if (!cl || cl.length < 2) return null;
              return <Line points={toFlat(cl)} stroke="#ef4444" strokeWidth={1.2}
                           dash={[5, 4]} opacity={0.4} lineCap="round" />;
            })()}

            {/* ── Contact strips — profile-category-specific rendering ──────── */}
            {showZones && (cur?.contact_strips ?? []).map((cs, i) => {
              const a = toCanvas(cs.x_from, cs.y_from);
              const b = toCanvas(cs.x_to,   cs.y_to);
              const rx = Math.min(a.cx, b.cx);
              const ry = Math.min(a.cy, b.cy);
              const rw = Math.abs(b.cx - a.cx) || 4;
              const rh = Math.abs(b.cy - a.cy) || 4;

              // strip_type → semantic color
              const STRIP_COLOR_MAP: Record<string, string> = {
                web_contact:         "#10b981",
                flange_contact:      "#3b82f6",
                chamfer_contact:     "#f59e0b",
                shutter_rib_contact: "#f59e0b",
                lip_contact:         "#06b6d4",
                rebate_contact:      "#a855f7",
              };
              const fillColor = STRIP_COLOR_MAP[cs.strip_type] ?? cs.color ?? "#94a3b8";
              const isWeb     = cs.strip_type === "web_contact";

              // Profile-category-specific visual treatment:
              // shutter_slat: narrow strips with dashed border (ribs are narrow + periodic)
              // door_frame / rebate_contact: thicker border + wider dash (rebate slot highlight)
              // lipped_channel / lip_contact: dotted border (thin lip contact)
              // default: solid border
              const isShutter   = profCat === "shutter_slat" || cs.strip_type === "shutter_rib_contact";
              const isDoorFrame = profCat === "door_frame"   || cs.strip_type === "rebate_contact";
              const isLip       = profCat === "lipped_channel" || cs.strip_type === "lip_contact";

              const strokeDash  = isShutter ? [3, 3] : isDoorFrame ? [5, 2] : isLip ? [1, 2] : undefined;
              const strokeW     = isDoorFrame ? 1.4 : isShutter ? 0.8 : 0.8;
              const fillOpacity = isWeb ? 0.15 : isShutter ? 0.09 : isDoorFrame ? 0.14 : 0.11;
              const borderOp    = isWeb ? 0.60 : isDoorFrame ? 0.55 : 0.40;

              // Shutter ribs: display as a narrowed horizontal band (half height, centred)
              const displayRy = isShutter ? ry + rh * 0.25 : ry;
              const displayRh = isShutter ? rh * 0.5        : rh;

              return (
                <Group key={i}>
                  <Rect x={rx} y={displayRy} width={rw} height={displayRh}
                        fill={fillColor} opacity={fillOpacity} />
                  <Rect x={rx} y={displayRy} width={rw} height={displayRh}
                        stroke={fillColor} strokeWidth={strokeW} dash={strokeDash}
                        opacity={borderOp} />
                </Group>
              );
            })}

            {/* ── Active profile (solid, glowing) ──────────────────────────── */}
            {activePts.length >= 2 && (
              <>
                {/* Shadow / glow */}
                <Line points={toFlat(activePts)} stroke={stageCol}
                      strokeWidth={5} opacity={0.12} lineCap="round" lineJoin="round" />
                {/* Main line */}
                <Line points={toFlat(activePts)} stroke={stageCol}
                      strokeWidth={2.5} lineCap="round" lineJoin="round" />
                {/* Vertex dots */}
                {activePts.map((p, i) => {
                  const { cx, cy } = toCanvas(p.x, p.y);
                  return (
                    <Circle key={i} x={cx} y={cy} radius={3}
                      fill={stageCol} opacity={0.9} />
                  );
                })}
              </>
            )}

            {/* ── Pinch zone markers — severity-aware with independent toggles ─ */}
            {(cur?.pinch_zones ?? []).map((pz, i) => {
              const isCritical = pz.severity === "critical";
              const isHigh     = pz.severity === "high";
              // Apply toggle logic: default-severity uses showPinch, high uses showHighPinch, critical uses showCritPinch
              const visible = isCritical ? (showPinch && showCritPinch)
                            : isHigh     ? (showPinch && showHighPinch)
                            : showPinch;
              if (!visible) return null;

              const { cx, cy } = toCanvas(pz.x, pz.y);
              const isFlange = pz.zone_type.includes("flange");
              const ringColor  = isCritical ? "#ef4444" : isHigh ? "#f97316" : "#f59e0b";
              const dotColor   = isCritical ? "#fca5a5" : isHigh ? "#fdba74" : "#fbbf24";
              const strokeW    = isCritical ? 2.0 : 1.2;
              // Severity label shown below the zone marker
              const sevLabel = isCritical ? "CRITICAL" : isHigh ? "HIGH" : null;
              return (
                <Group key={i}>
                  <Circle x={cx} y={cy} radius={isFlange ? 5 : 10}
                          fill={ringColor} opacity={0.18} />
                  <Circle x={cx} y={cy} radius={isFlange ? 3 : 5.5}
                          stroke={ringColor} strokeWidth={strokeW} opacity={0.85} />
                  <Circle x={cx} y={cy} radius={1.5} fill={dotColor} opacity={0.9} />
                  <Text
                    x={cx + 8} y={cy - 9}
                    text={pz.label}
                    fontSize={isCritical ? 8 : 7.5}
                    fill={dotColor}
                    fontFamily="monospace"
                    fontStyle={isCritical ? "bold" : "normal"}
                    opacity={0.9}
                  />
                  {sevLabel && (
                    <Text
                      x={cx + 8} y={cy + 3}
                      text={sevLabel}
                      fontSize={7}
                      fill={ringColor}
                      fontFamily="monospace"
                      fontStyle="bold"
                      opacity={0.85}
                    />
                  )}
                </Group>
              );
            })}

            {/* ── Entry / exit radius labels on the pass-line axis ─────────── */}
            {showZones && cur?.entry_radius_mm != null && (
              <Group>
                <Text
                  x={6} y={H - 44}
                  text={`Entry r = ${cur.entry_radius_mm}mm`}
                  fontSize={8} fill="#f59e0b" fontFamily="monospace" opacity={0.75}
                />
                <Text
                  x={6} y={H - 33}
                  text={`Exit  r = ${cur.exit_radius_mm ?? "—"}mm`}
                  fontSize={8} fill="#f59e0b" fontFamily="monospace" opacity={0.75}
                />
                {cur.edge_relief_width_mm != null && (
                  <Text
                    x={6} y={H - 22}
                    text={`Edge relief ${cur.edge_relief_width_mm}mm × ${cur.edge_relief_depth_mm?.toFixed(2) ?? "?"}mm`}
                    fontSize={8} fill="#94a3b8" fontFamily="monospace" opacity={0.65}
                  />
                )}
              </Group>
            )}

            {/* ── Contact point markers (red — existing bend-vertex detection) ─ */}
            {showContact && contactPts.map((p, i) => {
              const { cx, cy } = toCanvas(p.x, p.y);
              return (
                <Group key={i}>
                  <Circle x={cx} y={cy} radius={8} fill="#ef4444" opacity={0.2} />
                  <Circle x={cx} y={cy} radius={4} fill="#ef4444" opacity={0.85} />
                  <Circle x={cx} y={cy} radius={1.5} fill="#ffffff" opacity={0.9} />
                </Group>
              );
            })}

            {/* Dimension annotations */}
            {dims}

            {/* Station label */}
            <Text
              x={8} y={8} text={`${cur?.station_label ?? ""} — ${(cur?.target_angle_deg ?? 0).toFixed(1)}°`}
              fontSize={10} fill={stageCol} fontFamily="monospace" fontStyle="bold"
            />
            <Text
              x={8} y={20}
              text={hasReal ? "● real geometry" : "○ fallback"}
              fontSize={8.5} fill={hasReal ? "#22c55e" : "#6b7280"} fontFamily="monospace"
            />

            {/* Legend */}
            <Group x={W - 118} y={8}>
              <Rect x={0} y={0} width={112} height={88} fill="#0a0f1a" cornerRadius={4} opacity={0.85} />
              {[
                [stageCol,  "Current station"],
                ["#ef4444", "Final profile"],
                ["#60a5fa", "Web dim"],
                ["#4ade80", "Flange dim"],
                ["#ef4444", "Contact point"],
                ["#10b981", "Web contact zone"],
                ["#3b82f6", "Flange support"],
                ["#f59e0b", "Pinch / chamfer"],
              ].map(([col, lbl], i) => (
                <Group key={i} x={6} y={6 + i * 10}>
                  <Rect x={0} y={2} width={10} height={3} fill={col as string} cornerRadius={1} opacity={0.8} />
                  <Text x={14} y={0} text={lbl as string} fontSize={7.5}
                        fill="#64748b" fontFamily="monospace" />
                </Group>
              ))}
            </Group>

            {/* Geometry-source badge */}
            <Rect
              x={W / 2 - 55} y={H - 22} width={110} height={16}
              fill={hasReal ? "#052e16" : "#1c1917"} cornerRadius={3}
            />
            <Text
              x={W / 2 - 55} y={H - 18}
              text={hasReal ? `✓ section_centerline()` : `~ angle-transform fallback`}
              fontSize={8.5} fill={hasReal ? "#22c55e" : "#78716c"}
              fontFamily="monospace" width={110} align="center"
            />
          </Layer>
        </Stage>
      </div>

      {/* Controls */}
      <div className="px-4 py-2.5 border-t border-gray-700/50 flex items-center gap-2">
        <button onClick={() => go(0)} className="p-1.5 rounded text-gray-600 hover:text-white hover:bg-white/5 transition-colors">
          <SkipBack className="w-3.5 h-3.5" />
        </button>
        <button onClick={() => go(activeIdx - 1)} className="p-1.5 rounded text-gray-500 hover:text-white hover:bg-white/5 transition-colors">
          <ChevronLeft className="w-3.5 h-3.5" />
        </button>

        <div className="flex-1 mx-2">
          <input type="range" min={0} max={Math.max(0, n - 1)} value={activeIdx}
            onChange={e => go(Number(e.target.value))}
            className="w-full cursor-pointer" style={{ accentColor: stageCol }} />
        </div>

        <button onClick={() => go(activeIdx + 1)} className="p-1.5 rounded text-gray-500 hover:text-white hover:bg-white/5 transition-colors">
          <ChevronRight className="w-3.5 h-3.5" />
        </button>
        <button onClick={() => go(n - 1)} className="p-1.5 rounded text-gray-600 hover:text-white hover:bg-white/5 transition-colors">
          <SkipForward className="w-3.5 h-3.5" />
        </button>

        {cur && (
          <div className="text-[10px] font-mono shrink-0 text-right min-w-[120px]">
            <div style={{ color: stageCol }} className="font-semibold">{cur.station_label}</div>
            <div className="text-gray-600">{cur.target_angle_deg.toFixed(1)}° · {activeIdx + 1}/{n}</div>
          </div>
        )}
      </div>

      {/* Station pills */}
      <div className="px-4 pb-2 flex gap-1 overflow-x-auto">
        {passes.map((p, i) => {
          const sc     = STAGE_COL[p.stage_type] ?? "#60a5fa";
          const hasR   = (p.profile_centerline?.length ?? 0) >= 2;
          return (
            <button key={i} onClick={() => go(i)}
              title={`S${p.pass_no} ${p.target_angle_deg.toFixed(0)}° ${hasR ? "✓ real" : "~ fallback"}`}
              className="shrink-0 w-6 h-6 rounded-full text-[8px] font-bold transition-all border relative"
              style={i === activeIdx
                ? { background: sc + "40", borderColor: sc, color: sc }
                : { background: "transparent", borderColor: "#1e293b", color: "#475569" }}>
              {p.pass_no}
              {hasR && <span className="absolute -top-0.5 -right-0.5 w-1.5 h-1.5 rounded-full bg-green-500" />}
            </button>
          );
        })}
      </div>

      {/* Tooling-grade roll width breakdown info card */}
      {cur?.roll_width_breakdown && Object.keys(cur.roll_width_breakdown).length > 0 && (
        <div className="mx-3 mb-3 rounded-lg border border-gray-700/40 bg-[#080d14] px-3 py-2">
          <div className="text-[9px] font-bold text-gray-500 uppercase tracking-wider mb-1.5">
            Roll Face Width Breakdown — Station {cur.pass_no}
          </div>
          <div className="grid grid-cols-3 gap-x-3 gap-y-1">
            {[
              ["Web contact",     cur.roll_width_breakdown.web_contact_mm,       "#10b981"],
              ["Flange support",  cur.roll_width_breakdown.flange_support_mm,    "#3b82f6"],
              ["Edge relief ×2",  cur.roll_width_breakdown.edge_relief_mm,       "#f59e0b"],
              ["Shoulder ×2",     cur.roll_width_breakdown.shoulder_clearance_mm,"#94a3b8"],
              ["Total face",      cur.roll_width_breakdown.total_face_mm,        "#a78bfa"],
              ["Entry r",         cur.entry_radius_mm,                           "#f59e0b"],
            ].map(([label, val, color]) => val != null && (
              <div key={label as string} className="flex flex-col">
                <span className="text-[8px] text-gray-600 font-mono">{label as string}</span>
                <span className="text-[10px] font-bold font-mono" style={{ color: color as string }}>
                  {typeof val === "number" ? `${val.toFixed(2)}mm` : val}
                </span>
              </div>
            ))}
          </div>
          {cur.geometry_source && (
            <div className="mt-1.5 text-[8px] font-mono text-gray-600">
              src: {cur.geometry_source}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
