import React, { useState, useCallback } from "react";
import JSZip from "jszip";
import { useCncStore } from "../../store/useCncStore";
import { Download, FileText, Code2, Box, Loader2, CheckCircle2, Package } from "lucide-react";

interface ExportSection {
  id: string;
  label: string;
  desc: string;
  icon: React.ReactNode;
  color: string;
  ext: string;
}

const EXPORT_SECTIONS: ExportSection[] = [
  {
    id: "copra",
    label: "Copra RF — Roll Geometry Table",
    desc: "Per-station upper/lower roll profile coordinates in Copra-compatible CSV format",
    icon: <FileText className="w-4 h-4" />,
    color: "#06b6d4",
    ext: "csv",
  },
  {
    id: "solidworks",
    label: "SolidWorks Parameter Export",
    desc: "XML/CSV with all roll dimensions per station — import into SolidWorks as design table",
    icon: <Box className="w-4 h-4" />,
    color: "#a78bfa",
    ext: "xml",
  },
  {
    id: "solidcam",
    label: "SolidCAM G-Code — All Stations",
    desc: "SolidCAM-formatted G-code for each roll, ready to load in SolidCAM as turning operation",
    icon: <Code2 className="w-4 h-4" />,
    color: "#f59e0b",
    ext: "nc",
  },
  {
    id: "all",
    label: "Complete Export Package",
    desc: "All three exports in a single ZIP — Copra CSV + SolidWorks XML + all G-code files",
    icon: <Package className="w-4 h-4" />,
    color: "#22c55e",
    ext: "zip",
  },
];

function buildCopraCSV(rollTooling: ReturnType<typeof useCncStore.getState>["rollTooling"]): string {
  const lines: string[] = [
    "COPRA RF Compatible Roll Geometry Export",
    "Generated by Sai Rolotech Smart Engines",
    "",
    "Station,Roll,Profile_Type,Diameter_mm,Bore_mm,Width_mm,Groove_Depth_mm,Gap_mm,Upper_OD_mm,Lower_OD_mm,K_Factor,Pass_Line_Y",
  ];
  rollTooling.forEach(rt => {
    const rp = rt.rollProfile;
    lines.push([
      rt.stationNumber, "UPPER", "forming",
      rp.rollDiameter.toFixed(3), rp.shaftDiameter.toFixed(3), rp.rollWidth.toFixed(3),
      rp.grooveDepth.toFixed(3), rp.gap.toFixed(4), rp.rollDiameter.toFixed(3),
      (rp.rollDiameter - rp.grooveDepth * 2).toFixed(3), rp.kFactor.toFixed(4), rp.passLineY.toFixed(3),
    ].join(","));
    lines.push([
      rt.stationNumber, "LOWER", "forming",
      rp.rollDiameter.toFixed(3), rp.shaftDiameter.toFixed(3), rp.rollWidth.toFixed(3),
      "0.000", rp.gap.toFixed(4), rp.rollDiameter.toFixed(3), rp.rollDiameter.toFixed(3),
      rp.kFactor.toFixed(4), rp.passLineY.toFixed(3),
    ].join(","));

    // Profile coordinates
    lines.push(`# Station ${rt.stationNumber} Upper Roll Profile Coordinates`);
    lines.push("X_coord,Y_coord,Segment_Type");
    rp.upperRoll.forEach(seg => {
      lines.push(`${seg.startX.toFixed(4)},${seg.startY.toFixed(4)},${seg.type}`);
      lines.push(`${seg.endX.toFixed(4)},${seg.endY.toFixed(4)},${seg.type}`);
    });
    lines.push(`# Station ${rt.stationNumber} Lower Roll Profile Coordinates`);
    lines.push("X_coord,Y_coord,Segment_Type");
    rp.lowerRoll.forEach(seg => {
      lines.push(`${seg.startX.toFixed(4)},${seg.startY.toFixed(4)},${seg.type}`);
      lines.push(`${seg.endX.toFixed(4)},${seg.endY.toFixed(4)},${seg.type}`);
    });
    lines.push("");
  });
  return lines.join("\n");
}

function buildSolidWorksXML(rollTooling: ReturnType<typeof useCncStore.getState>["rollTooling"], materialType: string, thickness: number): string {
  const lines: string[] = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- SolidWorks Design Table Import — Sai Rolotech Smart Engines -->',
    '<RollFormingDesign>',
    `  <ProjectInfo material="${materialType}" thickness="${thickness}mm" stations="${rollTooling.length}" generated="${new Date().toISOString()}"/>`,
    '  <Stations>',
  ];
  rollTooling.forEach(rt => {
    const rp = rt.rollProfile;
    lines.push(`    <Station number="${rt.stationNumber}" label="${rt.label}">`);
    lines.push(`      <UpperRoll>`);
    lines.push(`        <OuterDiameter unit="mm">${rp.rollDiameter.toFixed(3)}</OuterDiameter>`);
    lines.push(`        <BoreDiameter unit="mm">${rp.shaftDiameter.toFixed(3)}</BoreDiameter>`);
    lines.push(`        <FaceWidth unit="mm">${rp.rollWidth.toFixed(3)}</FaceWidth>`);
    lines.push(`        <GrooveDepth unit="mm">${rp.grooveDepth.toFixed(3)}</GrooveDepth>`);
    lines.push(`        <RollGap unit="mm">${rp.gap.toFixed(4)}</RollGap>`);
    lines.push(`        <KFactor>${rp.kFactor.toFixed(4)}</KFactor>`);
    lines.push(`        <CenterlineY unit="mm">${rp.upperRollCenterY.toFixed(3)}</CenterlineY>`);
    lines.push(`        <ProfileCoords>`);
    rp.upperRoll.forEach((seg, i) => {
      lines.push(`          <Seg id="${i + 1}" type="${seg.type}" x1="${seg.startX.toFixed(4)}" y1="${seg.startY.toFixed(4)}" x2="${seg.endX.toFixed(4)}" y2="${seg.endY.toFixed(4)}"${seg.radius ? ` r="${seg.radius.toFixed(4)}"` : ""}/>`);
    });
    lines.push(`        </ProfileCoords>`);
    lines.push(`      </UpperRoll>`);
    lines.push(`      <LowerRoll>`);
    lines.push(`        <OuterDiameter unit="mm">${rp.rollDiameter.toFixed(3)}</OuterDiameter>`);
    lines.push(`        <BoreDiameter unit="mm">${rp.shaftDiameter.toFixed(3)}</BoreDiameter>`);
    lines.push(`        <FaceWidth unit="mm">${rp.rollWidth.toFixed(3)}</FaceWidth>`);
    lines.push(`        <CenterlineY unit="mm">${rp.lowerRollCenterY.toFixed(3)}</CenterlineY>`);
    lines.push(`      </LowerRoll>`);
    lines.push(`    </Station>`);
  });
  lines.push("  </Stations>");
  lines.push("</RollFormingDesign>");
  return lines.join("\n");
}

export function RollToolingExportPanel() {
  const { rollTooling, gcodeOutputs, materialType, materialThickness } = useCncStore();
  const [exporting, setExporting] = useState<string | null>(null);
  const [done, setDone] = useState<Set<string>>(new Set());

  const triggerDownload = (blob: Blob, filename: string) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = filename; a.click();
    URL.revokeObjectURL(url);
  };

  const doExport = useCallback(async (id: string) => {
    setExporting(id);
    await new Promise(r => setTimeout(r, 600));

    try {
      if (id === "all") {
        // Build a real ZIP package containing all export formats
        const zip = new JSZip();
        const copraFolder = zip.folder("copra");
        const swFolder = zip.folder("solidworks");
        const scFolder = zip.folder("solidcam");

        copraFolder?.file("copra-roll-geometry.csv", buildCopraCSV(rollTooling));
        swFolder?.file("solidworks-roll-params.xml", buildSolidWorksXML(rollTooling, materialType, materialThickness));

        if (gcodeOutputs.length > 0) {
          gcodeOutputs.forEach(go => {
            scFolder?.file(`station-${go.stationNumber}-${go.label.replace(/\s+/g, "_")}.nc`, go.gcode);
          });
        } else {
          scFolder?.file("no-gcode-placeholder.nc", "% No G-code generated yet — generate from the G-Code tab first\nM30\n%");
        }

        zip.file("README.txt", [
          "Roll Forming Tool Export Package",
          "=================================",
          `Exported: ${new Date().toISOString()}`,
          `Stations: ${rollTooling.length}`,
          `Material: ${materialType} @ ${materialThickness}mm`,
          "",
          "Contents:",
          "  copra/  — Copra RF CSV geometry files",
          "  solidworks/  — SolidWorks XML parameter files",
          "  solidcam/  — SolidCAM NC G-code programs",
        ].join("\n"));

        const zipBlob = await zip.generateAsync({ type: "blob", compression: "DEFLATE", compressionOptions: { level: 6 } });
        triggerDownload(zipBlob, "roll-tooling-export-package.zip");

      } else if (id === "copra") {
        const csv = buildCopraCSV(rollTooling);
        triggerDownload(new Blob([csv], { type: "text/csv" }), "copra-roll-geometry.csv");

      } else if (id === "solidworks") {
        const xml = buildSolidWorksXML(rollTooling, materialType, materialThickness);
        triggerDownload(new Blob([xml], { type: "application/xml" }), "solidworks-roll-params.xml");

      } else if (id === "solidcam") {
        if (gcodeOutputs.length > 0) {
          gcodeOutputs.forEach(go => {
            const blob = new Blob([go.gcode], { type: "text/plain" });
            triggerDownload(blob, `solidcam-station-${go.stationNumber}-${go.label.replace(/\s+/g, "_")}.nc`);
          });
        } else {
          const noGcode = "% No G-code generated yet — generate from the G-Code tab first\nM30\n%";
          triggerDownload(new Blob([noGcode], { type: "text/plain" }), "solidcam-no-gcode.nc");
        }
      }

      setDone(prev => new Set([...prev, id]));
    } finally {
      setExporting(null);
    }
  }, [rollTooling, gcodeOutputs, materialType, materialThickness]);

  const hasTooling = rollTooling.length > 0;
  const hasGcode = gcodeOutputs.length > 0;

  return (
    <div className="flex flex-col h-full bg-[#070710] overflow-hidden">
      <div className="flex-shrink-0 px-4 py-3 border-b border-white/[0.07] flex items-center gap-3">
        <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-600 to-cyan-600 flex items-center justify-center">
          <Download className="w-4 h-4 text-white" />
        </div>
        <div className="flex-1">
          <div className="text-sm font-bold text-white">Roll Tooling Export</div>
          <div className="text-[10px] text-zinc-500">Copra RF · SolidWorks · SolidCAM — production-ready exports</div>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-3">
        {/* Status summary */}
        <div className="grid grid-cols-3 gap-2">
          <div className={`rounded-lg border p-2.5 text-center ${hasTooling ? "border-emerald-500/25 bg-emerald-500/5" : "border-white/[0.07] bg-white/[0.02]"}`}>
            <div className={`text-lg font-bold ${hasTooling ? "text-emerald-400" : "text-zinc-600"}`}>{rollTooling.length}</div>
            <div className="text-[10px] text-zinc-600">Roll Sets</div>
          </div>
          <div className={`rounded-lg border p-2.5 text-center ${hasGcode ? "border-blue-500/25 bg-blue-500/5" : "border-white/[0.07] bg-white/[0.02]"}`}>
            <div className={`text-lg font-bold ${hasGcode ? "text-blue-400" : "text-zinc-600"}`}>{gcodeOutputs.length}</div>
            <div className="text-[10px] text-zinc-600">G-Code Files</div>
          </div>
          <div className="rounded-lg border border-white/[0.07] bg-white/[0.02] p-2.5 text-center">
            <div className="text-lg font-bold text-amber-400">{materialType}</div>
            <div className="text-[10px] text-zinc-600">{materialThickness}mm</div>
          </div>
        </div>

        {!hasTooling && (
          <div className="rounded-xl border border-amber-500/25 bg-amber-500/5 p-4 flex items-start gap-3">
            <div className="w-8 h-8 rounded-lg bg-amber-500/15 flex items-center justify-center flex-shrink-0">
              <FileText className="w-4 h-4 text-amber-400" />
            </div>
            <div>
              <div className="text-xs font-semibold text-amber-300 mb-1">No Roll Tooling Generated</div>
              <div className="text-[10px] text-zinc-500">Generate roll tooling in the Roll Tooling tab first. The exports will contain all per-station profiles and dimensions.</div>
            </div>
          </div>
        )}

        {EXPORT_SECTIONS.map(section => {
          const isExporting = exporting === section.id;
          const isDone = done.has(section.id);
          const isDisabled = !hasTooling && section.id !== "all";

          return (
            <div key={section.id} className="rounded-xl border border-white/[0.07] bg-white/[0.02] p-4">
              <div className="flex items-start gap-3">
                <div className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0"
                  style={{ background: `${section.color}15`, border: `1px solid ${section.color}30`, color: section.color }}>
                  {section.icon}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-xs font-semibold text-zinc-200">{section.label}</span>
                    {isDone && <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 flex-shrink-0" />}
                  </div>
                  <div className="text-[10px] text-zinc-500 leading-relaxed">{section.desc}</div>

                  <div className="flex items-center gap-2 mt-3">
                    <button
                      onClick={() => doExport(section.id)}
                      disabled={isExporting || (isDisabled && section.id !== "all")}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] font-semibold transition-all disabled:opacity-40 disabled:cursor-not-allowed"
                      style={{
                        background: `${section.color}18`,
                        border: `1px solid ${section.color}35`,
                        color: section.color,
                      }}
                    >
                      {isExporting ? (
                        <><Loader2 className="w-3 h-3 animate-spin" /> Exporting...</>
                      ) : (
                        <><Download className="w-3 h-3" /> Download .{section.ext}</>
                      )}
                    </button>
                    {isDone && (
                      <span className="text-[10px] text-emerald-400">Downloaded!</span>
                    )}
                  </div>
                </div>
              </div>
            </div>
          );
        })}

        {/* G-code file list */}
        {hasGcode && (
          <div className="rounded-xl border border-white/[0.07] bg-white/[0.02] p-4">
            <div className="text-[10px] font-semibold text-zinc-500 uppercase tracking-wider mb-3">G-Code Programs ({gcodeOutputs.length} files)</div>
            <div className="space-y-2">
              {gcodeOutputs.map(go => (
                <div key={go.stationNumber} className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Code2 className="w-3 h-3 text-zinc-600" />
                    <span className="text-[10px] text-zinc-400">Station {go.stationNumber} — {go.label}</span>
                    <span className="text-[9px] text-zinc-600">{go.lineCount} lines</span>
                  </div>
                  <button
                    onClick={() => {
                      const blob = new Blob([go.gcode], { type: "text/plain" });
                      const url = URL.createObjectURL(blob);
                      const a = document.createElement("a");
                      a.href = url;
                      a.download = `station-${go.stationNumber}-${go.label.replace(/\s+/g, "_")}.nc`;
                      a.click();
                      URL.revokeObjectURL(url);
                    }}
                    className="text-[10px] text-blue-400 hover:text-blue-300 transition-colors flex items-center gap-1"
                  >
                    <Download className="w-2.5 h-2.5" /> .nc
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
