import { create } from "zustand";
import { v4 as uuidv4 } from "uuid";
import * as THREE from "three";
import {
  performCSG,
  createRevolveGeometry,
  createSweepGeometry,
  createLoftGeometry,
  createShellGeometry,
  applyFilletToGeometry,
  applyChamferToGeometry,
  getDefaultProfile,
  type CSGOperation,
} from "./SolidModelingEngine";

export type PrimitiveType = "box" | "cylinder" | "sphere" | "cone";
export type SketchShapeType = "line" | "rect" | "circle";
export type ToolType = "end_mill" | "drill" | "face_mill" | "ball_nose";
export type StudioMode = "3d" | "sketch";

export type SceneObjectType =
  | PrimitiveType
  | "extrude"
  | "sketch"
  | "csg_result"
  | "revolve"
  | "sweep"
  | "loft"
  | "shell"
  | "fillet"
  | "chamfer";

export type FeatureType =
  | "primitive"
  | "extrude"
  | "csg_union"
  | "csg_subtract"
  | "csg_intersect"
  | "revolve"
  | "sweep"
  | "loft"
  | "shell"
  | "fillet"
  | "chamfer";

export interface FeatureNode {
  id: string;
  type: FeatureType;
  name: string;
  objectId: string;
  params: Record<string, unknown>;
  sourceObjectIds?: string[];
  timestamp: number;
  enabled: boolean;
}

export interface SceneObject {
  id: string;
  name: string;
  type: SceneObjectType;
  position: [number, number, number];
  rotation: [number, number, number];
  scale: [number, number, number];
  color: string;
  visible: boolean;
  sketchData?: SketchShape[];
  extrudeDepth?: number;
  customGeometry?: THREE.BufferGeometry;
}

export interface SketchShape {
  id: string;
  type: SketchShapeType;
  x: number;
  y: number;
  width?: number;
  height?: number;
  radius?: number;
  x2?: number;
  y2?: number;
}

export interface CAMSettings {
  toolType: ToolType;
  toolDiameter: number;
  cutDepth: number;
  stepover: number;
  feedRate: number;
  spindleSpeed: number;
  coolant: boolean;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: number;
}

interface Studio3DState {
  mode: StudioMode;
  objects: SceneObject[];
  selectedObjectId: string | null;
  camSettings: CAMSettings;
  generatedGcode: string | null;
  chatMessages: ChatMessage[];
  isChatLoading: boolean;
  sketchShapes: SketchShape[];
  activeSketchTool: SketchShapeType | "select";
  featureTree: FeatureNode[];
  secondarySelectionId: string | null;

  setMode: (mode: StudioMode) => void;
  addPrimitive: (type: PrimitiveType) => void;
  selectObject: (id: string | null) => void;
  setSecondarySelection: (id: string | null) => void;
  updateObject: (id: string, updates: Partial<SceneObject>) => void;
  deleteObject: (id: string) => void;
  setCamSettings: (settings: Partial<CAMSettings>) => void;
  generateGcode: () => void;
  addChatMessage: (role: "user" | "assistant", content: string) => void;
  setChatLoading: (loading: boolean) => void;
  addSketchShape: (shape: Omit<SketchShape, "id">) => void;
  clearSketchShapes: () => void;
  extrudeSketch: (depth: number) => void;
  setActiveSketchTool: (tool: SketchShapeType | "select") => void;

  performCSGOperation: (operation: CSGOperation) => void;
  addRevolve: (params: {
    profileType: "rect" | "circle" | "l-shape";
    profileSize: number;
    axis: "x" | "y";
    angle: number;
  }) => void;
  addSweep: (params: {
    profileType: "rect" | "circle" | "l-shape";
    profileSize: number;
    pathType: "line" | "arc" | "helix";
    pathLength: number;
  }) => void;
  addLoft: (params: {
    profile1Type: "rect" | "circle";
    profile1Size: number;
    profile2Type: "rect" | "circle";
    profile2Size: number;
    height: number;
  }) => void;
  applyShell: (thickness: number) => void;
  applyFillet: (radius: number) => void;
  applyChamfer: (distance: number) => void;

  toggleFeature: (featureId: string) => void;
  deleteFeature: (featureId: string) => void;
  reorderFeature: (featureId: string, direction: "up" | "down") => void;
  updateFeatureParams: (
    featureId: string,
    params: Record<string, unknown>
  ) => void;
}

const DEFAULT_CAM: CAMSettings = {
  toolType: "end_mill",
  toolDiameter: 6,
  cutDepth: 2,
  stepover: 0.5,
  feedRate: 1200,
  spindleSpeed: 18000,
  coolant: true,
};

function generateGcodeFromObject(obj: SceneObject, cam: CAMSettings): string {
  const lines: string[] = [];
  lines.push(`; G-Code generated by Sai Rolotech Smart Engines 3D Studio`);
  lines.push(`; Object: ${obj.name} (${obj.type})`);
  lines.push(
    `; Tool: ${cam.toolType.replace("_", " ").toUpperCase()} Ø${cam.toolDiameter}mm`
  );
  lines.push(
    `; Feed: ${cam.feedRate}mm/min | Spindle: ${cam.spindleSpeed}rpm`
  );
  lines.push(``);
  lines.push(`G21 ; Metric`);
  lines.push(`G90 ; Absolute positioning`);
  lines.push(`G17 ; XY plane`);
  lines.push(`M03 S${cam.spindleSpeed} ; Spindle on CW`);
  if (cam.coolant) lines.push(`M08 ; Coolant on`);
  lines.push(``);
  lines.push(`; --- Toolpath for ${obj.name} ---`);
  lines.push(`G00 Z5.0 ; Safe height`);

  const sx = obj.scale[0];
  const sy = obj.scale[2];
  const cx = obj.position[0];
  const cy = obj.position[2];
  const depth = cam.cutDepth;
  const passes = Math.ceil(depth / 1.0);

  for (let p = 1; p <= passes; p++) {
    const z = -(p * (depth / passes)).toFixed(3);
    lines.push(``);
    lines.push(`; Pass ${p}/${passes} — Z${z}`);
    lines.push(
      `G00 X${(cx - sx / 2).toFixed(3)} Y${(cy - sy / 2).toFixed(3)}`
    );
    lines.push(`G01 Z${z} F${(cam.feedRate * 0.3).toFixed(0)}`);
    lines.push(
      `G01 X${(cx + sx / 2).toFixed(3)} Y${(cy - sy / 2).toFixed(3)} F${cam.feedRate}`
    );
    lines.push(
      `G01 X${(cx + sx / 2).toFixed(3)} Y${(cy + sy / 2).toFixed(3)}`
    );
    lines.push(
      `G01 X${(cx - sx / 2).toFixed(3)} Y${(cy + sy / 2).toFixed(3)}`
    );
    lines.push(
      `G01 X${(cx - sx / 2).toFixed(3)} Y${(cy - sy / 2).toFixed(3)}`
    );
  }

  lines.push(``);
  lines.push(`G00 Z50.0 ; Retract`);
  if (cam.coolant) lines.push(`M09 ; Coolant off`);
  lines.push(`M05 ; Spindle stop`);
  lines.push(`M30 ; Program end`);
  lines.push(`%`);

  return lines.join("\n");
}

function generateSweepPath(
  pathType: "line" | "arc" | "helix",
  length: number
): Array<{ x: number; y: number; z: number }> {
  const points: Array<{ x: number; y: number; z: number }> = [];
  const steps = 32;

  switch (pathType) {
    case "line":
      for (let i = 0; i <= steps; i++) {
        points.push({ x: 0, y: (i / steps) * length, z: 0 });
      }
      break;
    case "arc":
      for (let i = 0; i <= steps; i++) {
        const t = (i / steps) * Math.PI;
        points.push({
          x: Math.sin(t) * length * 0.5,
          y: (i / steps) * length,
          z: (1 - Math.cos(t)) * length * 0.25,
        });
      }
      break;
    case "helix":
      for (let i = 0; i <= steps; i++) {
        const t = (i / steps) * Math.PI * 4;
        points.push({
          x: Math.cos(t) * length * 0.2,
          y: (i / steps) * length,
          z: Math.sin(t) * length * 0.2,
        });
      }
      break;
  }

  return points;
}

export const use3DStudioStore = create<Studio3DState>((set, get) => ({
  mode: "3d",
  objects: [],
  selectedObjectId: null,
  camSettings: DEFAULT_CAM,
  generatedGcode: null,
  chatMessages: [
    {
      id: uuidv4(),
      role: "assistant",
      content:
        "Hello! I'm your AI design assistant. I can help with CAD design, CAM settings, G-code questions, and 3D modeling tips. What would you like to know?",
      timestamp: Date.now(),
    },
  ],
  isChatLoading: false,
  sketchShapes: [],
  activeSketchTool: "rect",
  featureTree: [],
  secondarySelectionId: null,

  setMode: (mode) => set({ mode }),

  addPrimitive: (type) => {
    const names: Record<PrimitiveType, string> = {
      box: "Box",
      cylinder: "Cylinder",
      sphere: "Sphere",
      cone: "Cone",
    };
    const colors = [
      "#4488ff",
      "#44ff88",
      "#ff8844",
      "#ff44aa",
      "#88ffff",
      "#ffff44",
    ];
    const obj: SceneObject = {
      id: uuidv4(),
      name: `${names[type]} ${get().objects.filter((o) => o.type === type).length + 1}`,
      type,
      position: [Math.random() * 4 - 2, 0.5, Math.random() * 4 - 2],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      color: colors[get().objects.length % colors.length],
      visible: true,
    };

    const feature: FeatureNode = {
      id: uuidv4(),
      type: "primitive",
      name: obj.name,
      objectId: obj.id,
      params: { primitiveType: type },
      timestamp: Date.now(),
      enabled: true,
    };

    set((s) => ({
      objects: [...s.objects, obj],
      selectedObjectId: obj.id,
      featureTree: [...s.featureTree, feature],
    }));
  },

  selectObject: (id) => set({ selectedObjectId: id }),
  setSecondarySelection: (id) => set({ secondarySelectionId: id }),

  updateObject: (id, updates) => {
    set((s) => ({
      objects: s.objects.map((o) => (o.id === id ? { ...o, ...updates } : o)),
    }));
  },

  deleteObject: (id) => {
    set((s) => ({
      objects: s.objects.filter((o) => o.id !== id),
      selectedObjectId:
        s.selectedObjectId === id ? null : s.selectedObjectId,
      featureTree: s.featureTree.filter((f) => f.objectId !== id),
    }));
  },

  setCamSettings: (settings) => {
    set((s) => ({ camSettings: { ...s.camSettings, ...settings } }));
  },

  generateGcode: () => {
    const { objects, selectedObjectId, camSettings } = get();
    const obj = selectedObjectId
      ? objects.find((o) => o.id === selectedObjectId)
      : objects[0];
    if (!obj) {
      set({ generatedGcode: "; No objects in scene\n; Add a shape first" });
      return;
    }
    const gcode = generateGcodeFromObject(obj, camSettings);
    set({ generatedGcode: gcode });
  },

  addChatMessage: (role, content) => {
    const msg: ChatMessage = {
      id: uuidv4(),
      role,
      content,
      timestamp: Date.now(),
    };
    set((s) => ({ chatMessages: [...s.chatMessages, msg] }));
  },

  setChatLoading: (loading) => set({ isChatLoading: loading }),

  addSketchShape: (shape) => {
    const full: SketchShape = { id: uuidv4(), ...shape };
    set((s) => ({ sketchShapes: [...s.sketchShapes, full] }));
  },

  clearSketchShapes: () => set({ sketchShapes: [] }),

  extrudeSketch: (depth) => {
    const { sketchShapes, objects } = get();
    if (sketchShapes.length === 0) return;
    const id = uuidv4();
    const extruded: SceneObject = {
      id,
      name: `Extrude ${objects.filter((o) => o.type === "extrude").length + 1}`,
      type: "extrude",
      position: [0, depth / 2, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      color: "#6688ff",
      visible: true,
      sketchData: [...sketchShapes],
      extrudeDepth: depth,
    };

    const feature: FeatureNode = {
      id: uuidv4(),
      type: "extrude",
      name: extruded.name,
      objectId: id,
      params: { depth },
      timestamp: Date.now(),
      enabled: true,
    };

    set((s) => ({
      objects: [...s.objects, extruded],
      selectedObjectId: id,
      sketchShapes: [],
      mode: "3d",
      featureTree: [...s.featureTree, feature],
    }));
  },

  setActiveSketchTool: (tool) => set({ activeSketchTool: tool }),

  performCSGOperation: (operation) => {
    const { objects, selectedObjectId, secondarySelectionId } = get();

    const objA = objects.find((o) => o.id === selectedObjectId);
    const objB = objects.find((o) => o.id === secondarySelectionId);

    if (!objA || !objB || objA.id === objB.id) return;

    try {
      const resultGeo = performCSG(objA, objB, operation);
      const id = uuidv4();
      const opNames: Record<CSGOperation, string> = {
        union: "Union",
        subtract: "Subtract",
        intersect: "Intersect",
      };
      const resultObj: SceneObject = {
        id,
        name: `${opNames[operation]}(${objA.name}, ${objB.name})`,
        type: "csg_result",
        position: [0, 0, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        color: objA.color,
        visible: true,
        customGeometry: resultGeo,
      };

      const feature: FeatureNode = {
        id: uuidv4(),
        type: `csg_${operation}` as FeatureType,
        name: resultObj.name,
        objectId: id,
        params: { operation },
        sourceObjectIds: [objA.id, objB.id],
        timestamp: Date.now(),
        enabled: true,
      };

      set((s) => ({
        objects: [
          ...s.objects.filter(
            (o) => o.id !== objA.id && o.id !== objB.id
          ),
          resultObj,
        ],
        selectedObjectId: id,
        secondarySelectionId: null,
        featureTree: [...s.featureTree, feature],
      }));
    } catch (e) {
      console.error("CSG operation failed:", e);
    }
  },

  addRevolve: (params) => {
    const profile = getDefaultProfile(params.profileType, params.profileSize);
    const geo = createRevolveGeometry(
      profile,
      params.axis,
      params.angle,
      32
    );
    const id = uuidv4();
    const obj: SceneObject = {
      id,
      name: `Revolve ${get().objects.filter((o) => o.type === "revolve").length + 1}`,
      type: "revolve",
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      color: "#88aaff",
      visible: true,
      customGeometry: geo,
    };

    const feature: FeatureNode = {
      id: uuidv4(),
      type: "revolve",
      name: obj.name,
      objectId: id,
      params: { ...params },
      timestamp: Date.now(),
      enabled: true,
    };

    set((s) => ({
      objects: [...s.objects, obj],
      selectedObjectId: id,
      featureTree: [...s.featureTree, feature],
    }));
  },

  addSweep: (params) => {
    const profile = getDefaultProfile(params.profileType, params.profileSize);
    const path = generateSweepPath(params.pathType, params.pathLength);
    const geo = createSweepGeometry(profile, path, true);
    const id = uuidv4();
    const obj: SceneObject = {
      id,
      name: `Sweep ${get().objects.filter((o) => o.type === "sweep").length + 1}`,
      type: "sweep",
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      color: "#aa88ff",
      visible: true,
      customGeometry: geo,
    };

    const feature: FeatureNode = {
      id: uuidv4(),
      type: "sweep",
      name: obj.name,
      objectId: id,
      params: { ...params },
      timestamp: Date.now(),
      enabled: true,
    };

    set((s) => ({
      objects: [...s.objects, obj],
      selectedObjectId: id,
      featureTree: [...s.featureTree, feature],
    }));
  },

  addLoft: (params) => {
    const profile1 = getDefaultProfile(params.profile1Type, params.profile1Size);
    const profile2 = getDefaultProfile(params.profile2Type, params.profile2Size);
    const geo = createLoftGeometry(
      [
        { points: profile1, z: 0 },
        { points: profile2, z: params.height },
      ],
      16
    );
    const id = uuidv4();
    const obj: SceneObject = {
      id,
      name: `Loft ${get().objects.filter((o) => o.type === "loft").length + 1}`,
      type: "loft",
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      color: "#ffaa88",
      visible: true,
      customGeometry: geo,
    };

    const feature: FeatureNode = {
      id: uuidv4(),
      type: "loft",
      name: obj.name,
      objectId: id,
      params: { ...params },
      timestamp: Date.now(),
      enabled: true,
    };

    set((s) => ({
      objects: [...s.objects, obj],
      selectedObjectId: id,
      featureTree: [...s.featureTree, feature],
    }));
  },

  applyShell: (thickness) => {
    const { objects, selectedObjectId } = get();
    const obj = objects.find((o) => o.id === selectedObjectId);
    if (!obj) return;

    let sourceGeo: THREE.BufferGeometry;
    if (obj.customGeometry) {
      sourceGeo = obj.customGeometry;
    } else {
      const geoMap: Record<string, () => THREE.BufferGeometry> = {
        box: () =>
          new THREE.BoxGeometry(obj.scale[0], obj.scale[1], obj.scale[2]),
        cylinder: () =>
          new THREE.CylinderGeometry(
            0.5 * obj.scale[0],
            0.5 * obj.scale[0],
            obj.scale[1],
            32
          ),
        sphere: () =>
          new THREE.SphereGeometry(0.5 * obj.scale[0], 32, 16),
        cone: () =>
          new THREE.ConeGeometry(0.5 * obj.scale[0], obj.scale[1], 32),
      };
      const fn = geoMap[obj.type];
      if (!fn) return;
      sourceGeo = fn();
    }

    const shelledGeo = createShellGeometry(sourceGeo, thickness);
    const id = uuidv4();
    const newObj: SceneObject = {
      id,
      name: `Shell(${obj.name})`,
      type: "shell",
      position: obj.customGeometry ? [0, 0, 0] : [...obj.position],
      rotation: obj.customGeometry ? [0, 0, 0] : [...obj.rotation],
      scale: [1, 1, 1],
      color: obj.color,
      visible: true,
      customGeometry: shelledGeo,
    };

    const feature: FeatureNode = {
      id: uuidv4(),
      type: "shell",
      name: newObj.name,
      objectId: id,
      params: { thickness },
      sourceObjectIds: [obj.id],
      timestamp: Date.now(),
      enabled: true,
    };

    set((s) => ({
      objects: s.objects.map((o) => (o.id === obj.id ? newObj : o)),
      selectedObjectId: id,
      featureTree: [...s.featureTree, feature],
    }));
  },

  applyFillet: (radius) => {
    const { objects, selectedObjectId } = get();
    const obj = objects.find((o) => o.id === selectedObjectId);
    if (!obj) return;

    let sourceGeo: THREE.BufferGeometry;
    if (obj.customGeometry) {
      sourceGeo = obj.customGeometry;
    } else {
      const geoMap: Record<string, () => THREE.BufferGeometry> = {
        box: () =>
          new THREE.BoxGeometry(
            obj.scale[0],
            obj.scale[1],
            obj.scale[2],
            8,
            8,
            8
          ),
        cylinder: () =>
          new THREE.CylinderGeometry(
            0.5 * obj.scale[0],
            0.5 * obj.scale[0],
            obj.scale[1],
            32,
            8
          ),
        sphere: () =>
          new THREE.SphereGeometry(0.5 * obj.scale[0], 32, 16),
        cone: () =>
          new THREE.ConeGeometry(
            0.5 * obj.scale[0],
            obj.scale[1],
            32,
            8
          ),
      };
      const fn = geoMap[obj.type];
      if (!fn) return;
      sourceGeo = fn();
    }

    const filletedGeo = applyFilletToGeometry(sourceGeo, radius);
    const id = uuidv4();
    const newObj: SceneObject = {
      id,
      name: `Fillet(${obj.name})`,
      type: "fillet",
      position: obj.customGeometry ? [0, 0, 0] : [...obj.position],
      rotation: obj.customGeometry ? [0, 0, 0] : [...obj.rotation],
      scale: [1, 1, 1],
      color: obj.color,
      visible: true,
      customGeometry: filletedGeo,
    };

    const feature: FeatureNode = {
      id: uuidv4(),
      type: "fillet",
      name: newObj.name,
      objectId: id,
      params: { radius },
      sourceObjectIds: [obj.id],
      timestamp: Date.now(),
      enabled: true,
    };

    set((s) => ({
      objects: s.objects.map((o) => (o.id === obj.id ? newObj : o)),
      selectedObjectId: id,
      featureTree: [...s.featureTree, feature],
    }));
  },

  applyChamfer: (distance) => {
    const { objects, selectedObjectId } = get();
    const obj = objects.find((o) => o.id === selectedObjectId);
    if (!obj) return;

    let sourceGeo: THREE.BufferGeometry;
    if (obj.customGeometry) {
      sourceGeo = obj.customGeometry;
    } else {
      const geoMap: Record<string, () => THREE.BufferGeometry> = {
        box: () =>
          new THREE.BoxGeometry(
            obj.scale[0],
            obj.scale[1],
            obj.scale[2],
            8,
            8,
            8
          ),
        cylinder: () =>
          new THREE.CylinderGeometry(
            0.5 * obj.scale[0],
            0.5 * obj.scale[0],
            obj.scale[1],
            32,
            8
          ),
        sphere: () =>
          new THREE.SphereGeometry(0.5 * obj.scale[0], 32, 16),
        cone: () =>
          new THREE.ConeGeometry(
            0.5 * obj.scale[0],
            obj.scale[1],
            32,
            8
          ),
      };
      const fn = geoMap[obj.type];
      if (!fn) return;
      sourceGeo = fn();
    }

    const chamferedGeo = applyChamferToGeometry(sourceGeo, distance);
    const id = uuidv4();
    const newObj: SceneObject = {
      id,
      name: `Chamfer(${obj.name})`,
      type: "chamfer",
      position: obj.customGeometry ? [0, 0, 0] : [...obj.position],
      rotation: obj.customGeometry ? [0, 0, 0] : [...obj.rotation],
      scale: [1, 1, 1],
      color: obj.color,
      visible: true,
      customGeometry: chamferedGeo,
    };

    const feature: FeatureNode = {
      id: uuidv4(),
      type: "chamfer",
      name: newObj.name,
      objectId: id,
      params: { distance },
      sourceObjectIds: [obj.id],
      timestamp: Date.now(),
      enabled: true,
    };

    set((s) => ({
      objects: s.objects.map((o) => (o.id === obj.id ? newObj : o)),
      selectedObjectId: id,
      featureTree: [...s.featureTree, feature],
    }));
  },

  toggleFeature: (featureId) => {
    const feature = get().featureTree.find((f) => f.id === featureId);
    if (!feature) return;
    const newEnabled = !feature.enabled;
    set((s) => ({
      featureTree: s.featureTree.map((f) =>
        f.id === featureId ? { ...f, enabled: newEnabled } : f
      ),
      objects: s.objects.map((o) =>
        o.id === feature.objectId ? { ...o, visible: newEnabled } : o
      ),
    }));
  },

  deleteFeature: (featureId) => {
    const feature = get().featureTree.find((f) => f.id === featureId);
    if (!feature) return;
    set((s) => ({
      featureTree: s.featureTree.filter((f) => f.id !== featureId),
      objects: s.objects.filter((o) => o.id !== feature.objectId),
      selectedObjectId:
        s.selectedObjectId === feature.objectId
          ? null
          : s.selectedObjectId,
    }));
  },

  reorderFeature: (featureId, direction) => {
    set((s) => {
      const idx = s.featureTree.findIndex((f) => f.id === featureId);
      if (idx < 0) return s;
      const newIdx = direction === "up" ? idx - 1 : idx + 1;
      if (newIdx < 0 || newIdx >= s.featureTree.length) return s;
      const tree = [...s.featureTree];
      [tree[idx], tree[newIdx]] = [tree[newIdx], tree[idx]];
      return { featureTree: tree };
    });
  },

  updateFeatureParams: (featureId, params) => {
    set((s) => ({
      featureTree: s.featureTree.map((f) =>
        f.id === featureId ? { ...f, params: { ...f.params, ...params } } : f
      ),
    }));
  },
}));
