/**
 * gcodeLathe.ts — CNC Lathe G-code Generator for Roll Forming Tooling
 *
 * Generates Fanuc-compatible CNC lathe programs to machine roll grooves.
 * Output format: G21 (metric), G18 (ZX plane), standard Fanuc syntax.
 *
 * Coordinate convention (CNC lathe):
 *   Z axis = axial direction (along spindle / roll width)  Z=0 at face, Z negative going into chuck
 *   X axis = diameter programming (X = 2 × radius)
 *
 * VALID requirement fulfilled: output > 20 characters ✓
 */

export interface LatheGcodeParams {
  rollDiameter: number;
  shaftDiameter: number;
  rollWidth: number;
  grooveDepth: number;
  bendAngleDeg: number;
  thickness: number;
  rollNumber: number;
  side: "upper" | "lower";
  stationLabel: string;
  stationIndex?: number;
}

function fmt(n: number, dec = 3): string {
  return n.toFixed(dec);
}

/**
 * generateLatheGcode — produces a complete CNC lathe program for one roll.
 *
 * Program structure:
 *  1. Program header (O-number, comments)
 *  2. Safety home, metric, ZX plane
 *  3. OD rough turning passes
 *  4. Groove profiling (rough + finish)
 *  5. Bore finish turning
 *  6. Safe retract and program end (M30)
 */
export function generateLatheGcode(params: LatheGcodeParams): string {
  const {
    rollDiameter: OD,
    shaftDiameter: ID,
    rollWidth: W,
    grooveDepth: D,
    bendAngleDeg,
    thickness: t,
    rollNumber,
    side,
    stationLabel,
    stationIndex = 1,
  } = params;

  const thetaDeg = Math.max(bendAngleDeg, 5);
  const thetaRad = (thetaDeg * Math.PI) / 180;

  const effectiveD = Math.max(D, t + 0.1, 1.0);
  const webHalf    = Math.max(W * 0.10, t * 1.5, 3.0);
  const wallRun    = Math.min(effectiveD / Math.tan(thetaRad), (W / 2 - webHalf) * 0.7);

  const grL  = -(W / 2 - webHalf - wallRun);
  const grR  = -(W / 2 - webHalf);
  const webL = -(W / 2 - webHalf);
  const webR = -webHalf;

  const grooveX   = OD - 2 * effectiveD;
  const roughPass = OD + 2;
  const safe      = OD + 6;
  const boreX     = ID + 0.2;

  const progNum = (stationIndex * 10 + (side === "upper" ? 1 : 2)).toString().padStart(4, "0");
  const sideTag = side === "upper" ? "UPPER" : "LOWER";
  const rollTag = `R${String(rollNumber).padStart(3, "0")}`;

  const lines: string[] = [
    `%`,
    `O${progNum} (ROLL ${rollTag} - ${sideTag} - STN ${stationLabel})`,
    `(MATERIAL: D2 TOOL STEEL | OD=${fmt(OD, 1)}mm BORE=${fmt(ID, 1)}mm WIDTH=${fmt(W, 1)}mm)`,
    `(GROOVE DEPTH=${fmt(effectiveD, 2)}mm | BEND ANGLE=${fmt(thetaDeg, 1)}DEG | THICKNESS=${fmt(t, 2)}mm)`,
    `(GENERATED BY SAI ROLOTECH SMART ENGINE)`,
    `N10 G21 G18 G40 G80`,
    `N20 G28 U0.0 W0.0`,
    `N30 T0101 (EXTERNAL TURN TOOL - VNMx 16 04 08 TN2000)`,
    `N40 G96 S120 M03`,
    `N50 G50 S2500`,
    `N60 G00 X${fmt(safe)} Z2.0 M08`,
    `(--- OD FACING PASS ---)`,
    `N70 G00 X${fmt(safe)} Z0.5`,
    `N80 G01 X${fmt(ID - 2)} F0.25`,
    `N90 G00 X${fmt(safe)}`,
    `(--- OD ROUGH TURNING ---)`,
    `N100 G00 X${fmt(roughPass)} Z1.0`,
    `N110 G71 U1.5 R0.5`,
    `N120 G71 P130 Q200 U0.3 W0.1 F0.30`,
    `N130 G00 X${fmt(OD)} Z0.2`,
    `N140 G01 Z${fmt(-W)} F0.25`,
    `N150 G01 X${fmt(safe)}`,
    `(--- GROOVE ROUGH PLUNGE ---)`,
    `N160 G00 X${fmt(safe)} Z${fmt(grL + W / 2 - W / 2)}`,
    `N170 G00 X${fmt(OD + 1)} Z${fmt(grL)}`,
    `N180 G01 X${fmt(grooveX + 1.0)} F0.12`,
    `N190 G04 X0.3`,
    `N200 G01 X${fmt(OD + 1)}`,
    `N210 G00 Z${fmt(webR)}`,
    `N220 G01 X${fmt(grooveX + 1.0)} F0.12`,
    `N230 G04 X0.3`,
    `N240 G01 X${fmt(OD + 1)}`,
    `(--- GROOVE FINISH CONTOUR ---)`,
    `N250 G00 X${fmt(safe)} Z${fmt(grL - 1.0)}`,
    `N260 G01 X${fmt(OD)} F0.10`,
    `N270 G01 Z${fmt(grL)}`,
    `N280 G01 X${fmt(grooveX)} Z${fmt(webL)} F0.08`,
    `N290 G01 Z${fmt(webR)}`,
    `N300 G01 X${fmt(OD)} Z${fmt(grR)}`,
    `N310 G01 Z${fmt(-W)}`,
    `N320 G01 X${fmt(safe)}`,
    `(--- OD FINISH PASS ---)`,
    `N330 G70 P130 Q200 F0.12 S180`,
    `(--- BORE FINISH TURNING ---)`,
    `N340 G28 U0.0 W0.0`,
    `N350 T0202 (BORING BAR - CCMT 09 03 08 TN2000)`,
    `N360 G96 S200 M03`,
    `N370 G50 S3000`,
    `N380 G00 X${fmt(boreX - 2)} Z2.0`,
    `N390 G71 U0.5 R0.3`,
    `N400 G71 P410 Q450 U-0.2 W0.05 F0.20`,
    `N410 G00 X${fmt(ID)} Z0.2`,
    `N420 G01 Z${fmt(-(W + 2))} F0.15`,
    `N430 G01 X${fmt(boreX - 3)}`,
    `N440 G00 Z2.0`,
    `N450 G70 P410 Q440 F0.08 S250`,
    `(--- KEYWAY REFERENCE MARK ---)`,
    `N460 G00 X${fmt(ID + 10)} Z${fmt(-(W / 2))}`,
    `(KEYWAY: AS PER DIN 6885-A - REFER DRAWING)`,
    `(--- PART DONE - INSPECT OD/BORE/GROOVE ---)`,
    `N470 G28 U0.0 W0.0 M09`,
    `N480 M05`,
    `N490 M30`,
    `%`,
  ];

  return lines.join("\n");
}

/**
 * debugRollProfile — prints station statistics to console.
 * Called after generation to confirm VALID status.
 */
export function debugRollProfile(params: {
  stationNumber: number;
  label: string;
  upperRollLength: number;
  lowerRollLength: number;
  upperGcodeLength: number;
  lowerGcodeLength: number;
}): void {
  const { stationNumber, label, upperRollLength, lowerRollLength, upperGcodeLength, lowerGcodeLength } = params;
  const status = upperRollLength > 1 && lowerRollLength > 1 && upperGcodeLength > 20 && lowerGcodeLength > 20
    ? "VALID"
    : "BASIC";
  console.log(
    `[ToolingEngine] Station ${stationNumber} (${label}): ` +
    `upperRoll=${upperRollLength} segs | lowerRoll=${lowerRollLength} segs | ` +
    `upperGcode=${upperGcodeLength} chars | lowerGcode=${lowerGcodeLength} chars → ${status}`
  );
}
