import {
  pgTable,
  text,
  numeric,
  integer,
  timestamp,
  jsonb,
  uuid,
  boolean,
  real,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const cncTools = pgTable("cnc_tools", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: text("user_id").notNull(),
  name: text("name").notNull(),
  category: text("category").notNull(),
  subType: text("sub_type").notNull(),
  isoDesignation: text("iso_designation"),
  diameter: real("diameter"),
  fluteCount: integer("flute_count"),
  helixAngle: real("helix_angle"),
  fluteLength: real("flute_length"),
  overallLength: real("overall_length"),
  cornerRadius: real("corner_radius"),
  noseRadius: real("nose_radius"),
  noseAngle: real("nose_angle"),
  reliefAngle: real("relief_angle"),
  icDiameter: real("ic_diameter"),
  chipBreaker: text("chip_breaker"),
  coatingType: text("coating_type"),
  gradeCode: text("grade_code"),
  holderCode: text("holder_code"),
  holderReach: real("holder_reach"),
  holderOverhang: real("holder_overhang"),
  insertThickness: real("insert_thickness"),
  cuttingEdgeCount: integer("cutting_edge_count"),
  geometry: jsonb("geometry").default({}),
  notes: text("notes"),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").default(sql`NOW()`),
  updatedAt: timestamp("updated_at").default(sql`NOW()`),
});

export const cncToolCuttingData = pgTable("cnc_tool_cutting_data", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  toolId: uuid("tool_id").references(() => cncTools.id, { onDelete: "cascade" }).notNull(),
  materialId: uuid("material_id").references(() => cncMaterials.id, { onDelete: "cascade" }),
  operationType: text("operation_type").notNull(),
  vcRough: real("vc_rough"),
  feedRough: real("feed_rough"),
  docRough: real("doc_rough"),
  vcFinish: real("vc_finish"),
  feedFinish: real("feed_finish"),
  docFinish: real("doc_finish"),
  coolant: text("coolant").default("M08"),
  maxRpm: integer("max_rpm").default(3000),
  notes: text("notes"),
  createdAt: timestamp("created_at").default(sql`NOW()`),
});

export const cncMaterials = pgTable("cnc_materials", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  code: text("code").notNull().unique(),
  name: text("name").notNull(),
  category: text("category").notNull(),
  isoGroup: text("iso_group").notNull(),
  isoGroupLetter: text("iso_group_letter").notNull(),
  hardnessMin: real("hardness_min"),
  hardnessMax: real("hardness_max"),
  hardnessScale: text("hardness_scale").default("HB"),
  yieldStrength: real("yield_strength"),
  tensileStrength: real("tensile_strength"),
  elasticModulus: real("elastic_modulus"),
  density: real("density"),
  elongation: real("elongation"),
  thermalExpansion: real("thermal_expansion"),
  kFactor: real("k_factor"),
  springbackRatio: real("springback_ratio"),
  maxBendAngle: real("max_bend_angle"),
  minBendRadius: real("min_bend_radius"),
  machinability: real("machinability"),
  roughingVc: real("roughing_vc"),
  roughingFeed: real("roughing_feed"),
  roughingDoc: real("roughing_doc"),
  finishingVc: real("finishing_vc"),
  finishingFeed: real("finishing_feed"),
  finishingDoc: real("finishing_doc"),
  maxSurfaceSpeed: real("max_surface_speed"),
  minSurfaceSpeed: real("min_surface_speed"),
  hardnessFactor: real("hardness_factor").default(1.0),
  color: text("color").default("#a1a1aa"),
  isDefault: boolean("is_default").default(false),
  createdAt: timestamp("created_at").default(sql`NOW()`),
  updatedAt: timestamp("updated_at").default(sql`NOW()`),
});

export type CncTool = typeof cncTools.$inferSelect;
export type InsertCncTool = typeof cncTools.$inferInsert;
export type CncToolCuttingData = typeof cncToolCuttingData.$inferSelect;
export type InsertCncToolCuttingData = typeof cncToolCuttingData.$inferInsert;
export type CncMaterial = typeof cncMaterials.$inferSelect;
export type InsertCncMaterial = typeof cncMaterials.$inferInsert;
